### ISSUE TITLE
Hello, how to start this project

### ISSUE THREAD

**Issue by zpzp307** [gnvo/ekfoa#2]
Hello, how to start this project

**Comment by nv-pipo** [comment]
Hey there!
Sorry the delay.
It's been a long time since I worked on this project. There are other projects that are more robust mapping capabilities, which could be easily extended for obstacle avoidance. I recommend you having a look at:
https://github.com/tum-vision/lsd_slam
https://github.com/VIS4ROB-lab/ccm_slam
https://github.com/JakobEngel/dso
Good luck!
